// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// module.exports = {
//   docs: [
    // 'front-page',
    // 'welcome',
    // 'table-of-contents',
    // 'chapter1-introduction',
    // 'chapter2-history',
    // 'chapter3-types',
    // 'chapter4-components',
    // 'chapter5-future',
  // ],
// };
import {SidebarConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarConfig = {
  docs: [
    'Chapters/front-page',
    'Chapters/welcome',
    'Chapters/table-of-contents',
    'Chapters/chapter1-introduction',
    'Chapters/chapter2-history',
    'Chapters/chapter3-types',
    'Chapters/chapter4-components',
    'Chapters/chapter5-future',
  ],
};

export default sidebars;

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
// };

// export default sidebars;
